### ISSUE TITLE
Not working with the latest node versions

### ISSUE THREAD

**Issue by saeedjabbar** [bshambaugh/nist-weierstrauss#5]
Getting the errors below as it's expecting node 8.18.3. nvm only has node 8.17.0.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nist-weierstrauss@1.5.1',
npm WARN EBADENGINE   required: { node: '>=14.06' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```

**Comment by bshambaugh** [comment]
I realized I did not publish to npm the latest pull request removing the engine property from package.json. 
https://github.com/bshambaugh/nist-weierstrauss/pull/4

I'll look more into it, but hopefully this does the trick.

**Comment by bshambaugh** [comment]
This has the same behavior as what you were getting.  I am quite confident now that your problem is solved. 

https://www.wisdomgeek.com/development/web-development/javascript/how-to-prevent-npm-install-for-unsupported-node-js-versions/

**Comment by saeedjabbar** [comment]
Thanks!!
